version: "2.1"

services:

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:v2.1.5
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "5000"
      BITCOIN_HOST: "164.132.216.52"
      BITCOIN_ZMQ_RAWBLOCK_PORT: "29001"
      BITCOIN_ZMQ_RAWTX_PORT: "29002"
      BITCOIN_RPC_PORT: "8332"
      BITCOIN_RPC_USER: "user"
      BITCOIN_RPC_PASS: "pass"
    ports:
      - "5555:5000"